- Automation:
    - GithubActions:
        href: https://github.com/lucassimpson0213/homelab-dashboard/actions
        description: Homelab Github Actions
        icon: github.png

- Observability:
    - Grafana:
        href: http://100.67.62.26:3000
        ping: http://100.67.62.26:3000
        description: Homelab dashboards
        icon: grafana.png

    - Prometheus:
        href: http://100.67.62.26:9090
        ping: http://100.67.62.26:9090
        description: Metrics and monitoring
        icon: prometheus.png
- Backups:
    - Google Drive:
        href: https://drive.google.com/drive/my-drive
        description: Duplicati Backups

- Network:
    - Pi-hole:
        href: http://100.95.142.72/admin
        ping: http://100.95.142.72/admin
        description: DNS and network filtering
        icon: pi-hole.png

    - MikroTik:
        href: http://192.168.88.1
        ping: http://192.168.88.1
        description: Router and network management
        icon: mikrotik.png

    - Tailscale:
        href: https://login.tailscale.com/admin/machines
        description: Homelab mesh network
        icon: tailscale.png

- Backups & Storage:
    - Duplicati:
        href: https://app.duplicati.com/app/machines
        description: Centralized backup management
        icon: duplicati.png
    - Fedora Duplicati:
        href: http://100.111.153.92:8200
        description: duplicati on fedora mac
        icon: duplicati.png

    - Databasus:
        href: http://100.111.153.92:4005
        description: Database backups

    - MinIO:
        href: http://100.95.142.72:9001
        ping: http://100.95.142.72.9001
        description: Object storage
        icon: minio.png

- Management:
    - GitHub:
        href: https://github.com/lucassimpson0213
        description: Homelab source and configuration
        icon: github.png
    - Semaphore:
        href: http://100.111.153.92:3000
        ping: http://100.111.153.92:3000
        description: Ansible automation
        icon: semaphore.png

    - Portainer:
        href: https://100.111.153.92:9443
        ping: https://100.111.153.92:9443
        description: Docker management
        icon: portainer.png
    - Bitwarden:
       href: https://vault.bitwarden.com/#/vault
       description: Centralized secrets manager
       icon: bitwarden.png


- Hosts:
    - Hawk / Raspberry Pi:
        icon: cockpit.png
        href: https://100.95.142.72:9095
        ping: https://100.95.142.72:9095
        description: Cockpit host management

    - HP Desktop:
        icon: cockpit.png
        href: https://100.65.51.13:9095
        ping: https://100.65.51.13:9095
        description: Cockpit host management

    - Fedora Lenovo:
        icon: cockpit.png
        href: https://100.67.62.26:9095

        ping: https://100.67.62.26:9095
        description: Cockpit host management

    - Fedora Mac:
        icon: cockpit.png
        href: https://100.111.153.92:9095
        ping: https://100.111.153.92:9095
        description: Cockpit host management

- Personal:
  - Actual Budget:
     href: https://macbook2020.mulley-triggerfish.ts.net/
     ping: https://macbook2020.mulley-triggerfish.ts.net/
     description: budgeting application
  - Project management:
     href: https://linear.app/lucas-simpson/team/LUC/active
     description: Project management solution
  - Git Branching:
     href: https://learngitbranching.js.org/?locale=en_US
     description: git branching training
